#ifndef CONSTANTS_H
#define CONSTANTS_H

#define OUTPUT_TRAINING_FILE_NAME "outputTraining.txt"
#define ERROR_OUTPUT_TRAINING_FILE_NAME "errorOutputTraining.txt"
#define OUTPUT_RESULT_FILE_NAME "outputResult.txt"

#define QINT_VALIDATOR_MIN 0

#define FIRST_WIDGET_INDEX 0

//      ---     WIDGET POSITION     ---

//MIRROR WIDGET
#define ROW_MIRROR_WIDGET_TITLE 0
#define COLUMN_MIRROR_WIDGET_TITLE 0
#define ROW_SPAN_MIRROR_WIDGET_TITLE 1
#define COLUMN_SPAN_MIRROR_WIDGET_TITLE 1

#define ROW_HORIZONTAL_CHECK_BOX 1
#define COLUMN_HORIZONTAL_CHECK_BOX 0
#define ROW_SPAN_HORIZONTAL_CHECK_BOX 2
#define COLUMN_SPAN_HORIZONTAL_CHECK_BOX 1

#define ROW_VERTICAL_CHECK_BOX 2
#define COLUMN_VERTICAL_CHECK_BOX 0
#define ROW_SPAN_VERTICAL_CHECK_BOX 2
#define COLUMN_SPAN_VERTICAL_CHECK_BOX 1

#define ROW_DELETE_WIDGET_BUTTON 0
#define COLUMN_DELETE_WIDGET_BUTTON 1
#define ROW_SPAN_DELETE_WIDGET_BUTTON 1
#define COLUMN_SPAN_DELETE_WIDGET_BUTTON 1

//MORPHOLOGICAL_TRANSFORMATION WIDGET
#define MORPHOLOGICAL_TRANSFORMATION_MINIMUM_KERNEL_SIZE 1
#define MORPHOLOGICAL_TRANSFORMATION_MAXIMUM_KERNEL_SIZE 20

#define MORPHOLOGICAL_TRANSFORMATION_MINIMUM_NUMBER_ITERATION 1
#define MORPHOLOGICAL_TRANSFORMATION_MAXIMUM_NUMBER_ITERATION 10

#define ROW_MORPHOLOGICAL_TRANSFORMATION_WIDGET_TITLE 0
#define COLUMN_MORPHOLOGICAL_TRANSFORMATION_WIDGET_TITLE 0

#define ROW_MORPHOLOGICAL_TRANSFORMATION_TYPE 1
#define COLUMN_MORPHOLOGICAL_TRANSFORMATION_TYPE 0

#define ROW_MORPHOLOGICAL_TRANSFORMATION_KERNEL_SIZE_SLIDER 2
#define COLUMN_MORPHOLOGICAL_TRANSFORMATION_KERNEL_SIZE_SLIDER 0

#define ROW_MORPHOLOGICAL_TRANSFORMATION_NUMBER_ITERATION 3
#define COLUMN_MORPHOLOGICAL_TRANSFORMATION_NUMBER_ITERATION 0

#define ROW_MORPHOLOGICAL_TRANSFORMATION_DELETE_WIDGET_BUTTON 0
#define COLUMN_MORPHOLOGICAL_TRANSFORMATION_DELETE_WIDGET_BUTTON 1

//      ---     IMAGES_PREVIEW      ---

#define IMAGES_PREVIEW_MAXIMUM_ROWS 2
#define IMAGES_PREVIEW_MAXIMUM_COLLUMNS 5
#define IMAGES_PREVIEW_MAIN_LAYOUT_SPACING 1
#define IMAGES_PREVIEW_MAIN_LAYOUT_MARGIN 1
#define ROW_IMAGES_PREVIEW_IMAGES_LAYOUT 0
#define COLUMN_IMAGES_PREVIEW_IMAGES_LAYOUT 0
#define ROW_SPAN_IMAGES_PREVIEW_IMAGES_LAYOUT 3
#define COLUMN_SPAN_IMAGES_PREVIEW_IMAGES_LAYOUT 3

#define ROW_IMAGES_PREVIEW_PREVIOUS_BUTTON 3
#define COLUMN_IMAGES_PREVIEW_PREVIOUS_BUTTON 0
#define ROW_SPAN_IMAGES_PREVIEW_PREVIOUS_BUTTON 1
#define COLUMN_SPAN_IMAGES_PREVIEW_PREVIOUS_BUTTON 1

#define ROW_IMAGES_PREVIEW_NEXT_BUTTON 3
#define COLUMN_IMAGES_PREVIEW_NEXT_BUTTON 2
#define ROW_SPAN_IMAGES_PREVIEW_NEXT_BUTTON 1
#define COLUMN_SPAN_IMAGES_PREVIEW_NEXT_BUTTON 1

//      ---     Preprocessing Tab       ---

#define ROW_PREPROCESSING_TAB_PREVIEW_WIDGET 0
#define COLUMN_PREPROCESSING_TAB_PREVIEW_WIDGET 0
#define ROW_SPAN_PREPROCESSING_TAB_PREVIEW_WIDGET 3
#define COLUMN_SPAN_PREPROCESSING_TAB_PREVIEW_WIDGET 3

#define ROW_PREPROCESSING_TAB_TRANSFORMATION_VIEWER 0
#define COLUMN_PREPROCESSING_TAB_TRANSFORMATION_VIEWER 3
#define ROW_SPAN_PREPROCESSING_TAB_TRANSFORMATION_VIEWER 3
#define COLUMN_SPAN_PREPROCESSING_TAB_TRANSFORMATION_VIEWER 1

#define ROW_PREPROCESSING_TAB_SAVE_BUTTON 2
#define COLUMN_PREPROCESSING_TAB_SAVE_BUTTON 3
#define ROW_SPAN_PREPROCESSING_TAB_SAVE_BUTTON 1
#define COLUMN_SPAN_PREPROCESSING_TAB_SAVE_BUTTON 1

//      ---     Result Tab       ---

#define ROW_RESULT_TAB_CLASSIFICATION_PARAMETERS_LAYOUT 0
#define COLUMN_RESULT_TAB_CLASSIFICATION_PARAMETERS_LAYOUT 0

#define ROW_RESULT_TAB_RESULT_OUTPUT_LAYOUT 1
#define COLUMN_RESULT_TAB_RESULT_OUTPUT_LAYOUT 0


#endif // CONSTANTS_H